databases:
  - name: HomeStockManagerDB
    databaseName: homestockmanagerdb_0sko
    user: homestockmanagerdb_qki3_user
    region: singapore

services:
  - type: web
    name: HomeStockManager
    env: ruby
    region: singapore
    plan: free
    buildCommand:
      bundle install;
      yarn install;
      bundle exec rake assets:precompile;
      bundle exec rake db:migrate;

    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: HomeStockManagerDB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: cron
    name: HomeStockManagerCron
    env: ruby
    plan: starter
    region: singapore
    buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean;
    startCommand: bundle exec rails runner "Item.update_all_stocks"
    schedule: 0 0 * * *
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: HomeStockManagerDB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
