databases:
  - name: HomeStockManagerDB
    databaseName: homestockmanagerdb_0sko
    user: HomeStockManager
    region: singapore

services:
  - type: web
    name: HomeStockManager
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: HomeStockManagerDB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
