version: 2.1

jobs:
  run_rspec:
    docker:
      - image: cimg/ruby:3.2.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Run rspec
          command: bundle exec rspec

  deploy_to_render:
    docker:
      - image: curlimages/curl:7.83.1  # curlイメージを使用
    steps:
      - run:
          name: Deploy to Render
          command: |
            curl -X POST \
              -H "Accept: application/json" \
              -H "Authorization: Bearer ${RENDER_API_KEY}" \
              -d '{}' \
              https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - run_rspec
      - deploy_to_render:
          requires:
            - run_rspec
          filters:
            branches:
              only: main  # デプロイを行うブランチを指定
