version: 2.1

jobs:
  run_rspec:
    docker:
      - image: cimg/ruby:3.2  # Rubyバージョンに応じて適切なイメージを指定
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install  # 必要なGemをインストール
      - run:
          name: Run rspec
          command: bundle exec rspec  # rspecを実行

workflows:
  version: 2
  test:
    jobs:
      - run_rspec:
          filters:
            branches:
              only:
                - main  # 必要に応じてテストを実行するブランチを指定
